const metroCostTiers = {
    "New York-Northern New Jersey-Long Island, NY-NJ-PA": "High",
    "San Jose-Sunnyvale-Santa Clara, CA": "High",
    "San Francisco-Oakland-Fremont, CA": "High",
    "Bridgeport-Stamford-Norwalk, CT": "High",
    "Oxnard-Thousand Oaks-Ventura, CA": "High",
    "Honolulu, HI": "High",
    "Santa Cruz-Watsonville, CA": "High",
    "Vallejo-Fairfield, CA": "High",
    "Napa, CA": "High",
    "Boston-Cambridge-Quincy, MA-NH": "High",
    "Santa Rosa-Petaluma, CA": "High",
    "San Diego-Carlsbad-San Marcos, CA": "High",
    "Washington-Arlington-Alexandria, DC-VA-MD-WV": "High",
    "Los Angeles-Long Beach-Santa Ana, CA": "High",
    "Manchester-Nashua, NH": "High",
    "Salinas, CA": "High",
    "Santa Barbara-Santa Maria-Goleta, CA": "High",
    "Poughkeepsie-Newburgh-Middletown, NY": "High",
    "Sacramento-Arden-Arcade-Roseville, CA": "High",
    "Trenton-Ewing, NJ": "High",
    "Seattle-Tacoma-Bellevue, WA": "High",
    "New Haven-Milford, CT": "High",
    "San Luis Obispo-Paso Robles, CA": "High",
    "Stockton, CA": "High",
    "Portland-South Portland-Biddeford, ME": "High",
    "Riverside-San Bernardino-Ontario, CA": "High",
    "Hartford-West Hartford-East Hartford, CT": "High",
    "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD": "High",
    "Chicago-Naperville-Joliet, IL-IN-WI": "High",
    "Worcester, MA": "High",
    "Norwich-New London, CT": "High",
    "Providence-New Bedford-Fall River, RI-MA": "High",
    "Barnstable Town, MA": "High",
    "Modesto, CA": "High",
    "Naples-Marco Island, FL": "Medium",
    "Boulder, CO": "Medium",
    "Anchorage, AK": "Medium",
    "Miami-Fort Lauderdale-Pompano Beach, FL": "Medium",
    "Minneapolis-St. Paul-Bloomington, MN-WI": "Medium",
    "Atlantic City, NJ": "Medium",
    "Portland-Vancouver-Beaverton, OR-WA": "Medium",
    "Austin-Round Rock, TX": "Medium",
    "Baltimore-Towson, MD": "Medium",
    "Ann Arbor, MI": "Medium",
    "Dallas-Fort Worth-Arlington, TX": "Medium",
    "Phoenix-Mesa-Scottsdale, AZ": "Medium",
    "Bremerton-Silverdale, WA": "Medium",
    "Kingston, NY": "Medium",
    "Burlington-South Burlington, VT": "Medium",
    "Mount Vernon-Anacortes, WA": "Medium",
    "Olympia, WA": "Medium",
    "Las Vegas-Paradise, NV": "Medium",
    "Atlanta-Sandy Springs-Marietta, GA": "Medium",
    "Ocean City, NJ": "Medium",
    "Denver-Aurora, CO": "Medium",
    "Allentown-Bethlehem-Easton, PA-NJ": "Medium",
    "Detroit-Warren-Livonia, MI": "Medium",
    "Lewiston-Auburn, ME": "Medium",
    "Houston-Sugar Land-Baytown, TX": "Medium",
    "Orlando-Kissimmee, FL": "Medium",
    "Reno-Sparks, NV": "Medium",
    "Merced, CA": "Medium",
    "Albany-Schenectady-Troy, NY": "Medium",
    "Rochester, NY": "Medium",
    "Fairbanks, AK": "Medium",
    "Bellingham, WA": "Medium",
    "Indianapolis-Carmel, IN": "Medium",
    "Springfield, MA": "Medium",
    "Corvallis, OR": "Medium",
    "Nashville-Davidson-Murfreesboro-Franklin, TN": "Medium",
    "Bend, OR": "Medium",
    "Raleigh-Cary, NC": "Medium",
    "Jacksonville, FL": "Medium",
    "Salt Lake City, UT": "Medium",
    "Kennewick-Richland-Pasco, WA": "Medium",
    "Bangor, ME": "Medium",
    "Dover, DE": "Medium",
    "Lancaster, PA": "Medium",
    "Redding, CA": "Medium",
    "Fresno, CA": "Medium",
    "Charleston-North Charleston, SC": "Medium",
    "Palm Coast, FL": "Medium",
    "Memphis, TN-MS-AR": "Medium",
    "Virginia Beach-Norfolk-Newport News, VA-NC": "Medium",
    "Madera, CA": "Medium",
    "Madison, WI": "Medium",
    "Milwaukee-Waukesha-West Allis, WI": "Medium",
    "Richmond, VA": "Low",
    "Syracuse, NY": "Low",
    "Buffalo-Niagra, NY": "Low",
    "Rochester, NY": "Low",
    "Albany, NY": "Low",
    "Charlottesville, VA": "Low",
    "Pittsfield, MA": "Low",
    "Colorado Springs, CO": "Low",
    "Cleveland-Elyria-Mentor, OH": "Low",
    "Omaha-Council Bluffs, NE-IA": "Low",
    "Rochester, MN": "Low",
    "Cincinnati-Middletown, OH-KY-IN": "Low",
    "Durham, NC": "Low",
    "Tallahassee, FL": "Low",
    "Longview, WA": "Low",
    "Prescott, AZ": "Low",
    "Spokane, WA": "Low",
    "Provo-Orem, UT": "Low",
    "Hanford-Corcoran, CA": "Low",
    "Boise City-Nampa, ID": "Low",
    "Hagerstown-Martinsburg, MD-WV": "Low",
    "Sebastian-Vero Beach, FL": "Low",
    "Eugene-Springfield, OR": "Low",
    "San Antonio, TX": "Low",
    "Louisville-Jefferson County, KY-IN": "Low",
    "Santa Fe, NM": "Low",
    "Columbia, SC": "Low",
    "Kansas City, MO-KS": "Low",
    "Jackson, MS": "Low",
    "Lansing-East Lansing, MI": "Low",
    "Elkhart-Goshen, IN": "Low",
    "Palm Bay-Melbourne-Titusville, FL": "Low",
    "Wenatchee, WA": "Low",
    "Rockford, IL": "Low",
    "Fort Walton Beach-Crestview-Destin, FL": "Low",
    "Akron, OH": "Low",
    "Racine, WI": "Low",
    "Bloomington-Normal, IL": "Low",
    "El Centro, CA": "Low",
    "Little Rock-North Little Rock-Conway, AR": "Low",
    "Lexington-Fayette, KY": "Low",
    "Medford, OR": "Low",
    "Visalia-Porterville, CA": "Low",
    "Pittsburgh, PA": "Low",
    "Des Moines-West Des Moines, IA": "Low",
    "Gainesville, GA": "Low",
    "Fayetteville-Springdale-Rogers, AR-MO": "Low",
    "Grand Rapids-Wyoming, MI": "Low",
    "State College, PA": "Low",
    "Deltona-Daytona Beach-Ormond Beach, FL": "Low",
    "Winchester, VA-WV": "Low",
    "Birmingham-Hoover, AL": "Low",
    "Coeur d'Alene, ID": "Low",
    "Lafayette, IN": "Low",
    "Baton Rouge, LA": "Low",
    "Killeen-Temple-Fort Hood, TX": "Low",
    "Savannah, GA": "Low",
    "Lincoln, NE": "Low",
    "Corpus Christi, TX": "Low",
    "Pensacola-Ferry Pass-Brent, FL": "Low",
    "Gainesville, FL": "Low",
    "Lake Havasu City-Kingman, AZ": "Low",
    "Columbus, IN": "Low",
    "Jackson, TN": "Low",
    "St. Louis, MO-IL": "Low",
    "Lebanon, PA": "Low",
    "St. Cloud, MN": "Low"
};

// Optional: Create a case-insensitive search helper
metroCostTiers.findMetro = function(searchTerm) {
    const normalizedSearch = searchTerm.toLowerCase().trim();
    for (const metro in this) {
        if (metro.toLowerCase().includes(normalizedSearch)) {
            return { name: metro, tier: this[metro] };
        }
    }
    return null;
};
